import os
import sys
import requests
import google.generativeai as genai
from google.api_core.exceptions import ResourceExhausted

def generate_with_resilience(prompt, api_key):
    genai.configure(api_key=api_key)
    # Execution is complex: Try Pro first, fallback to Flash
    primary = "gemini-2.5-pro"
    fallback = "gemini-2.5-flash"
    
    try:
        print(f"Executing heavy compute via {primary}...")
        return genai.GenerativeModel(primary).generate_content(prompt).text.strip()
    except ResourceExhausted:
        print(f"⚠️ 429 Error on {primary}. Engaging Fallback Cascade: {fallback}...")
        try:
            return genai.GenerativeModel(fallback).generate_content(prompt).text.strip()
        except Exception as e:
            return f"CRITICAL BRAIN FAILURE: {e}"

def parse_github_url(url):
    parts = url.rstrip('/').split('/')
    if "issues" in parts:
        i = parts.index("issues")
        return parts[i-2], parts[i-1], parts[i+1]
    return None, None, None

def main():
    api_key = os.getenv("GEMINI_API_KEY")
    github_token = os.getenv("SKEIN_GITHUB_TOKEN")
    wallet_address = os.getenv("RABBY_ADDRESS", "WALLET_NOT_CONFIGURED")
    target_url = os.getenv("TARGET_ISSUE_URL")
    
    if not all([api_key, github_token, target_url]):
        sys.exit(1)

    owner, repo, issue_number = parse_github_url(target_url)
    
    # 1. Get Context
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}"
    res = requests.get(url, headers={"Authorization": f"token {github_token}", "Accept": "application/vnd.github.v3+json"})
    if res.status_code != 200: sys.exit(1)
    issue_data = res.json()

    # 2. Classify (Engagement or Technical)
    class_prompt = f"Is this issue asking for a technical code fix, OR is it an engagement/marketing bounty (asking users to star repos/drop wallets)? Reply ONLY with 'TECHNICAL' or 'ENGAGEMENT'.\nBody: {issue_data.get('body')[:1000]}"
    classification = generate_with_resilience(class_prompt, api_key).upper()
    print(f"Target locked. Classification: {classification}")

    # 3. Generate Payload
    if "ENGAGEMENT" in classification:
        # Star the repo
        requests.put(f"https://api.github.com/user/starred/{owner}/{repo}", headers={"Authorization": f"token {github_token}", "Content-Length": "0"})
        prompt = f"Write a casual 2-sentence comment claiming this engagement bounty. Acknowledge the project. Provide this wallet address: {wallet_address}"
        payload = generate_with_resilience(prompt, api_key) + "\n\n---\n*Task executed autonomously by the Sovereign Skein.*"
    else:
        prompt = f"Provide a highly technical code fix or architectural breakdown for this bug report: {issue_data.get('title')} - {issue_data.get('body')[:1500]}"
        payload = generate_with_resilience(prompt, api_key) + "\n\n---\n*Analysis generated by Sovereign Skein agent.*"

    # 4. Strike
    strike_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"
    strike_res = requests.post(strike_url, headers={"Authorization": f"token {github_token}", "Accept": "application/vnd.github.v3+json"}, json={"body": payload})
    print("SUCCESS: Mission Accomplished." if strike_res.status_code == 201 else f"FAILED: {strike_res.text}")

if __name__ == "__main__":
    main()
